[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian = "2xETnXSFhwUs9c1BJZHwWib2jQMnYdUGL3QbtewVfA2y"

[programs.devnet]
meridian = "2xETnXSFhwUs9c1BJZHwWib2jQMnYdUGL3QbtewVfA2y"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "127.0.0.1"

[[test.validator.clone]]
address = "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY"

[[test.validator.clone]]
address = "PSMxQbAoDWDbvd9ezQJgARyq6R9L5kJAasaLDVcZwf1"

[scripts]
test = "pnpm exec tsx --test tests/integration/program/phoenix-bootstrap.test.ts"

[workspace]
members = ["programs/meridian"]

