export const DEFAULT_PUBLIC_SOLANA_CLUSTER = "devnet";

export const mirroredPublicKeyEnvFields = [
  ["MERIDIAN_PROGRAM_ID", "NEXT_PUBLIC_MERIDIAN_PROGRAM_ID"],
  ["MERIDIAN_USDC_MINT", "NEXT_PUBLIC_MERIDIAN_USDC_MINT"],
  ["MERIDIAN_PHOENIX_PROGRAM_ID", "NEXT_PUBLIC_MERIDIAN_PHOENIX_PROGRAM_ID"],
  ["MERIDIAN_PYTH_RECEIVER_PROGRAM_ID", "NEXT_PUBLIC_MERIDIAN_PYTH_RECEIVER_PROGRAM_ID"],
] as const;
