import {
  DEVNET_USDC_MINT,
  MERIDIAN_PHOENIX_PROGRAM_ID,
  MERIDIAN_PROGRAM_ID,
  MERIDIAN_PYTH_PRICE_PROGRAM_ID,
  MERIDIAN_PYTH_RECEIVER_PROGRAM_ID,
} from "@meridian/domain";

export const VALID_BOOTSTRAP_ENV = {
  SOLANA_RPC_URL: "https://api.devnet.solana.com",
  ANCHOR_WALLET: "fixtures/anchor-wallet.json",
  MERIDIAN_PROGRAM_ID,
  MERIDIAN_PROGRAM_KEYPAIR: "fixtures/program-keypair.json",
  MERIDIAN_USDC_MINT: DEVNET_USDC_MINT,
  MERIDIAN_PHOENIX_PROGRAM_ID,
  MERIDIAN_PHOENIX_SEAT_MANAGER_PROGRAM_ID: "PSMxQbAoDWDbvd9ezQJgARyq6R9L5kJAasaLDVcZwf1",
  MERIDIAN_PHOENIX_TAKER_FEE_BPS: "0",
  MERIDIAN_PHOENIX_MARKET_AUTHORITY_MODE: "seat-manager",
  MERIDIAN_PYTH_RECEIVER_PROGRAM_ID,
  MERIDIAN_PYTH_PRICE_PROGRAM_ID,
  NEXT_PUBLIC_SOLANA_CLUSTER: "devnet",
  NEXT_PUBLIC_SOLANA_RPC_URL: "https://api.devnet.solana.com",
  NEXT_PUBLIC_MERIDIAN_PROGRAM_ID: MERIDIAN_PROGRAM_ID,
  NEXT_PUBLIC_MERIDIAN_USDC_MINT: DEVNET_USDC_MINT,
  NEXT_PUBLIC_MERIDIAN_PHOENIX_PROGRAM_ID: MERIDIAN_PHOENIX_PROGRAM_ID,
  NEXT_PUBLIC_MERIDIAN_PYTH_RECEIVER_PROGRAM_ID: MERIDIAN_PYTH_RECEIVER_PROGRAM_ID,
} as const;
